apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Access mode for the volume
  resources:
    requests:
      storage: 1Gi  # Storage size requested for the volume

